spring.application.name=service
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8082/oauth2/jwks
spring.threads.virtual.enabled=true